version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - '3005:3005'
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - '4173:4173'

volumes:
  mongo-data:
